### ISSUE TITLE
Farm HNZ 

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#105]
Farm in NC it went down because gateway was knock over by something (presumably a person with a baseball) gateway needs to be replaced. gateway got full of water.

**Comment by annabirnbaum** [comment]
Baseball is a fun plot twist!

Anna Paulk Birnbaum

Agricultural Specialist
UGA-Department of Crop and Soil Sciences
1420 Experiment Station Rd
Watkinsville, GA 30677
C: 404-889-1688
________________________________
From: elhenriq ***@***.***>
Sent: Monday, June 14, 2021 2:56 PM
To: precision-sustainable-ag/On-farm-Protocols ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [precision-sustainable-ag/On-farm-Protocols] Farm HNZ (#105)

[EXTERNAL SENDER - PROCEED CAUTIOUSLY]


Farm in NC it went down because gateway was knock over by something (presumably a person with a baseball) gateway needs to be replaced. gateway got full of water.

**Comment by elhenriq** [comment]
There was an actual baseball next to it in the field ![image](https://user-images.githubusercontent.com/52674578/121946979-82fb7880-cd23-11eb-9b8c-ed02782eafc0.jpeg)![image](https://user-images.githubusercontent.com/52674578/121946982-84c53c00-cd23-11eb-83e3-bf0404519b7d.jpeg)

**Comment by annabirnbaum** [comment]
WOW someone REALLY doesn’t like the sensors

Anna Paulk Birnbaum

Agricultural Specialist
UGA-Department of Crop and Soil Sciences
1420 Experiment Station Rd
Watkinsville, GA 30677
C: 404-889-1688
________________________________
