### ISSUE TITLE
TXE AL Node Data SOS

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#108]
kip and I got the data off his nodes at TXE.  i added drive link to spreadsheet. today is the 15th, the nodes stopped recording data on the 13th (415) and 12th (431, 463,485).  He is worried. 

Do the nodes run out of space to record data at a certain point if not uploading to gateway?? @alondrathompson 

We didn't download data off the gateway today (are we supposed to or did we decide no?)

**Comment by alondrathompson** [comment]
The nodes do eventually run out of memory but they'll just erase the oldest data and start over. It would take a lot of data to get to that point though.

From: annabirnbaum ***@***.***>
Sent: Tuesday, June 15, 2021 4:40 PM
To: precision-sustainable-ag/On-farm-Protocols ***@***.***>
Cc: Thompson, Alondra - ARS ***@***.***>; Mention ***@***.***>
Subject: [precision-sustainable-ag/On-farm-Protocols] TXE AL Node Data SOS (#108)


kip and I got the data off his nodes at TXE. i added drive link to spreadsheet. today is the 15th, the nodes stopped recording data on the 13th (415) and 12th (431, 463,485). He is worried.

Do the nodes run out of space to record data at a certain point if not uploading to gateway?? @alondrathompson<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falondrathompson&data=04%7C01%7C%7C9ce134f8bf234320a71a08d9303dbe1b%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637593864012342316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=I%2Buq%2FwYxGxCvVH2TBeYkTC1DXYzWVzmFRMnVGeF7kok%3D&reserved=0>

We didn't download data off the gateway today (are we supposed to or did we decide no?)

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fprecision-sustainable-ag%2FOn-farm-Protocols%2Fissues%2F108&data=04%7C01%7C%7C9ce134f8bf234320a71a08d9303dbe1b%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637593864012342316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Zjy8SDHXuHByl%2FOkJdS%2BBGY%2B5yGXR%2FdmZoViVOkflRQ%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMQHBSBYRHXY3DKH3SLXQYDTS63B5ANCNFSM46YAFZPA&data=04%7C01%7C%7C9ce134f8bf234320a71a08d9303dbe1b%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637593864012352266%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BoGN6PYsPYt%2F3xyW%2FKFP%2F%2BZYD6dEKH%2B9rmNGHXHt7Fs%3D&reserved=0>.




This electronic message contains information generated by the USDA solely for the intended recipients. Any unauthorized interception of this message or the use or disclosure of the information it contains may violate the law and subject the violator to civil or criminal penalties. If you believe you have received this message in error, please notify the sender and delete the email immediately.

**Comment by annabirnbaum** [comment]
okay, so this is a mystery issue..

**Comment by screberg** [comment]
This seems like part of the communication problem we are having.
Unfortunately, the communication problem is preventing the nodes from
logging because they are stuck trying to talk to the gateway.  We need to
shut down communications at this site and put the node into logging mode
only.  We didn't have time to walk through that process but Alondra and
Esleyther can do a walk through of the menu choices.

Chris

Chris Reberg-Horton

Professor of Cropping Systems

University Faculty Scholar

Department of Crop and Soil Sciences, Campus Box 7620

NC State University

Raleigh, NC 27695-7620

919 515-7597

***@***.***

**Comment by annabirnbaum** [comment]
Yes, I had forgotten we had discussed this when I was on the phone with Kip yesterday.

I know how to put them into logging node, I had to do this for a few sites last year, I’ll call him back today.

I’m confused because I thought the updated firmware prevented this issue from happening and that they would continue to log data even with gateway issues.


Anna Paulk Birnbaum

Agricultural Specialist
UGA-Department of Crop and Soil Sciences
1420 Experiment Station Rd
Watkinsville, GA 30677
C: 404-889-1688
________________________________

**Comment by alondrathompson** [comment]
@annabirnbaum I thought so too. :/

**Comment by annabirnbaum** [comment]
I know this is oversimplification, but can the firmware code be written to tell the nodes to keep recording even if they can’t get in touch with the gateway? Is it a storage issue?

What programming language do you use for the firmware? My husband is a programmer, maybe we can bribe him into helping....

Getting desperate.

Anna Paulk Birnbaum

Agricultural Specialist
UGA-Department of Crop and Soil Sciences
1420 Experiment Station Rd
Watkinsville, GA 30677
C: 404-889-1688
________________________________

**Comment by alondrathompson** [comment]
@annabirnbaum It can be, but I have to balance PSA's needs with the variable rate irrigation project's needs. The VRI relies on the communication working since the sensor data informs the irrigation. 

The current firmware _should_ only wait for time span of the interval + 1 minute to reconnect with a gateway after three consecutive misses and then move on until the counter reaches 3 again. That should mean that with a 15 minute interval the node should at least be getting 3/4 of the data. But there's obviously something not working. There shouldn't be a storage issue, at least not in terms of capacity. These are things I'll be testing this week.

The firmware is in Arduino C.

**Comment by annabirnbaum** [comment]
Thanks Alondra.

Anna Paulk Birnbaum

Agricultural Specialist
UGA-Department of Crop and Soil Sciences
1420 Experiment Station Rd
Watkinsville, GA 30677
C: 404-889-1688
________________________________
