### ISSUE TITLE
Node re-sending same old data string over and over

### ISSUE THREAD

**Issue by miagodb** [precision-sustainable-ag/On-farm-Protocols#139]
In device view, UHC (NE) appears to be working and logging the data live. In chart view, the last point was recorded on June 2. I noticed that the timestamp printed in the code says 6-2-2021 so even though we were getting regular updates from the gateway and nodes, the nodes/sensors were recording data with the date of June 2.

https://onfarmtech.org/devices/280915

Tauana is going to visit this site sometime next week.

**Comment by saseehav** [comment]
Device: 280915(85594)
Issue was partially solved. The Gateway was receiving and sending many strings of data every minute ** timestamped from March and June**, being sent by the nodes over and over every minute, which is why it would not show up in the chart view. 
The timestamp is from earlier this year. 
1. Why was the gateway sending so much data every minute?
2. Why old timestamps? Node timeclock off? Node storing old data and trying to send it?

**Comment by alondrathompson** [comment]
@miagodb @saseehav 
It looks like the gateway is resending the same data over and over. Only the gateway string is up-to-date. It's consistently taking about 10 minutes to upload everything and it always ends with a string from 2021-6-2_22:30:00_UTC. Is this the gateway that needed to have its SD card swapped out? 

Since it's not sending any new data, my guess is that it has lost connection with the nodes and for some reason the dump file in the SD card isn't getting deleted. The nodes have also probably stalled because they haven't heard from the gateway and may be stuck in an infinite loop that V2021.04.14 ends up in if the right conditions happen simultaneously. 

If Tauana wants to try to fix the gateway, she can try swapping out the SD card and reset the entire system. Otherwise, she should turn off the gateway and put the nodes is data logging mode only.

**Comment by saseehav** [comment]
NOY also doing this

@miagodb put the device ID here and maybe a screenshot of the data string

**Comment by miagodb** [comment]
NOY: 164681(42951)
![Screenshot (2)](https://user-images.githubusercontent.com/85519047/125836812-506f1316-e3c7-4d4a-a77e-95961bccea7c.png)

UHC
![Screenshot (4)](https://user-images.githubusercontent.com/85519047/125837122-6d679966-444c-4639-abf4-d49ecf30468e.png)

**Comment by alondrathompson** [comment]
@miagodb @saseehav Erasing the SD card may fix that. Menu option e deletes everything on the card.
