### ISSUE TITLE
Roeser bag dates

### ISSUE THREAD

**Issue by deannrp** [precision-sustainable-ag/On-farm-Protocols#157]
Have a question about site VOP bags. All of my bags from that site  seem to have missing collection dates and I have no idea why. The rest of my sites are fine.

**Comment by brianwdavis** [comment]
I only see missing dates from time 0 and time 3 pickups. Time 0 is a piece of the logic that we can fix on our end, but time 3 is due to an error in the form submission. 

![image](https://user-images.githubusercontent.com/13338560/144093332-069e8ec4-d898-4eeb-b3eb-b4af524f47f4.png)

If you select "**Forms**" and then "**psa_bag_collect**", you'll see your history of submissions for bag pickups. If you choose the "Please Fix" tab, you'll see the broken submission:


![image](https://user-images.githubusercontent.com/13338560/144093665-45c986d4-21af-433e-9384-213ba063395d.png)


At the bottom you can se it's telling you there's an error in "group_001/barcode_bag_001", and if you look at the value listed, it's "34341049", instead of a barcode. So this is just an error in the scanner and the sticker on the bag not working right. You can choose "Edit form" at the bottom to change that value and resubmit the form into the pipeline.

![image](https://user-images.githubusercontent.com/13338560/144094116-614ac3b5-f2a8-4e42-a4db-927ff1c20040.png)

There you can type into the field on the right. Note that the formatting must match the correct barcodes **exactly**. My personal guess at the correct value for this field is "VOP-2-A-3". Below I've looked up the only rows for VOP that are missing dates in the database:

|code|subplot|subsample|time|recovery_date|
|----|-------|---------|----|-------------|
|VOP |1      |A        |0   |             |
|VOP |1      |B        |0   |             |
|VOP |2      |A        |0   |             |
|VOP |2      |B        |0   |             |
|VOP |1      |A        |3   |     |
|VOP |1      |B        |3   |     |
|VOP |2      |A        |3   |      |
|VOP |2      |B        |3   |      |

The "time 0" is something I'm going to handle programmatically, but the time 3 needs to be filled in. We see that we have valid scans for "VOP-2-B-3", "VOP-1-B-3", "VOP-1-A-3", so by process of elimination I came up with "VOP-2-A-3". However, I'm not in the position to be editing data this way, this should be a decision by the technical user (you) and the data shepherd if necessary (Resham).

So if you make that change, it will resubmit the form with the corrected barcode, and then it will be correctly processed into the database. Then it should show up in your tab for "**Valid Forms**" and I can confirm for you that it was parsed successfully.

Also if this comes into your email as a garbled mess and you can't see the formatting, I'm happy to go through all this in a zoom call!

**Comment by deannrp** [comment]
This made perfect sense and I believe I fixed that error just now. Thanks!!!
