### ISSUE TITLE
Weeds 3D camera connection

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#163]
Kip in Alabama called about having issues with the protocol on weeds 3D because he couldn't connect his gopro.

**Comment by elhenriq** [comment]
I ended up removing all connections from his tablet and camera (basically disconnecting everything from one another) and connecting everything back up again. Connecting first the GoPro with the app, and then entering the Wi-Fi password by hand (QR code did not work). After that, we tested for a few minutes, and it seems t o be working.

**Comment by saseehav** [comment]
@marialauracangiano

**Comment by marialauracangiano** [comment]
Sometimes the connection issue is due to the camera not being updated. Before factory resetting the camera please make sure that is not that you need to update the camera. Also, whenever you factory reset a camera please create an issue with the camera name and new password and who has the camera so we can generate a new QR code and change this in our records.
