### ISSUE TITLE
CFZ - water sensors not recording data DE

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/On-farm-Protocols#205]
went offline 6/17 right after installation. Never recorded Rep 2 Bare.

**Comment by kldriver** [comment]
@elhenriq Do we know what has been going on with this site? Is there data being collected there?

**Comment by elhenriq** [comment]
contacted team to sort this out

**Comment by elhenriq** [comment]
was contacted by the tech in DE today. he visited this farm, and we were able to check each node for data.

BT1 this device had issues with the solar panel from the very start and died due to energy. we were able to fix it now and should be collecting data. 

CT1 this device was collecting data well until 8-9, but it stopped collecting and never came back on after that. no apparent issues here other than the middle sensors working only sometimes. 

BT2 this node had a broken cable from the junction box to the node, but they didn't notice up until now. we fixed it and it was fine. no data in it since start of season. 

CT2 all the data was good on this device.
