### ISSUE TITLE
Water Sensors- DDQ MD

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#212]
This site went completely offline on 07/13/2022. Rep 1 and 2 Bare were last to go offline on 07/13 while Rep 1 Cover went down last month and has never sent surface sensor data. Rep 2 Cover sent data for a few hours on 6/17 and then went off again. 

Are the sensors not sending data connected correctly? Does this site need a reset? Other attention?

**Comment by ethansweep** [comment]
One of the nodes at this site was wrecked by some machinery, so it is getting replaced soon. That may have been why it went down. I have checked the wiring in the past, and everything looks good but I'll check again. 
Alondra is also giving us a 4G card for this site, which might help some of the issues? This gateway is about 10ft from the gateway for QVX, so I'm unsure why this one is having issues and that one is not.

**Comment by ethansweep** [comment]
This gateway was updated with a 4G SIM card this afternoon and connected with the gateway after a reset, but has not communicated with the dashboard any time since then.

The gateway has only sent two successful time updates and a message the same as VQQ (#245): 

{"new_imei": "865456055988016", "prev_imei": "014682005382220", "msg": "Device 1724909 IMEI change from 014682005382220 to 865456055988016"} | Wednesday, May 18th 2022, 2:37:58 PM
-- | --
