### ISSUE TITLE
Water Sensors- EOB

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#219]
This site never made an initial connection. Is it collecting data? Has there been troubleshooting?

**Comment by ethansweep** [comment]
Emailed Ryan on 12 July with the following issues and recommendations: 

System never made initial contact with the dashboard
- Make sure that the gateway and nodes are all turned on
- Plug into the nodes and gateway to see if the collected any data while it’s been installed

Reset the whole system

Add farm code to the tech dashboard

**Comment by elhenriq** [comment]
I spoke with Ronaldo last week he was able to download the data from these nodes, and they seem to be collection data no issues except for Bare 1. he is there today replacing all the TRD's to that treatment because I can not tell what was going on, all the sensors went bad. 

he will load the data to the drive later this week.

**Comment by saseehav** [comment]
Was Ronaldo given access to the Google Shared Drive and the Tech Dashboard? I don't have his contact information. @kldriver if you get his email from Esleyther can you begin onboarding him?

**Comment by elhenriq** [comment]
he was contacted, but he hasn't done anything yet. he started creating the GitHub account, but that's as far as he got (he said that on the phone).

**Comment by elhenriq** [comment]
Update: 

he reinstalled all the sensors for B1, and they are all working now. as a reminder, this farm is receiver mode only, so no data will be coming in. but all nodes are working fine now.
