### ISSUE TITLE
Water Sensors- HBM VA W

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#221]
SIte went completely offline 07/04/2022. Not great cellular connection with the last transmission. Has someone reached out to Cynthia to see if we have the data on the nodes and/or gateway and it's just not sending? Can we reset or troubleshoot to get this back online or is it just fine to be offline and collecting and connecting when it can?

**Comment by ethansweep** [comment]
Emailed Cynthia the following: 

This field site hasn’t been communicating with the tech dashboard since 07/04/22
- The gateway is only communicating with nodes #18000469, #18001860, #18000439.
- Find the fourth node that is not one of these three and see if it’s turned on and working correctly

The 75cm sensor depth connected to node #18000469 is showing a string of -999, which means there is some kind of error
- Pull the sensor out of the ground and check if the tines are bent in any way
- You will need a post puller for this

Try resetting the nodes and gateway to see if that resolves the issue

Print off the logs for this field from the nodes and gateway and email them to Ethan 

While plugged into the gateway set it to “Receiver Mode”

This field site isn’t showing up on the chart view due to an error in the psa_water_sensor_install form.
- Go onto the tech dashboard and located the forms that you have submitted
- Go to the “Please Fix” tab and correct any errors made in submitting the form
