### ISSUE TITLE
Water Sensors- NFT Indigo

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#226]
Indigo site NFT went offline fully 07/10/2022. Up until then, it was logging successfully. Last transmission shows fair-poor signal quality.

**Comment by ethansweep** [comment]
This site looks to be up and running again. It's sending complete data strings for all of four nodes that are visible on the device view.
@brianwdavis @mikahpinegar the chart view for this site hasn't updated since 07/10/22 even though the strings are coming in. Node #18000472 is showing -999 for all of the sensor depths, except the 10cm sensor

**Comment by kldriver** [comment]
This site's nodes are offline again as of 08/08/2022. The gateway is still transmitting time stamps though.
