### ISSUE TITLE
Water Sensors- SKF NE

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#232]
No longer listed in tech dashboard, did we pull this site offline?

**Comment by elhenriq** [comment]
@saseehav do you know anything about this? I am contacting Tauana to check what happened.

**Comment by elhenriq** [comment]
RESPONSE FROM TAUANA
![image](https://user-images.githubusercontent.com/52674578/181349810-75982bac-63cf-4a26-974f-5490db73a316.png)

Hi Esleyther, 

Please, see the picture attached. I did a reinstallation in SKF on June 28th, and sent the form on June 29th. 
What can I do? Do I need to go there to download the data? 

About the QAQ, I don’t know what happened, I can go there and download the data.

**Comment by elhenriq** [comment]
I was going over the installation forms that she submitted, and they are giving this "Error 0: `["['farm_info_group/crop_planting_date']"]` row failed tests for table farm_history__water_sensor_install". when I click on them to try and fix it, I don't have a way to add the planting date on the options.  the same thing applies for both this farm, SKF and QAQ. 
@mikahpinegar 
she had to do reinstalled because of some issues with the nodes.

**Comment by kldriver** [comment]
I did not see an upload of data in the folder for SKF. Do we have a status update for this site?

**Comment by elhenriq** [comment]
data was downloaded from them. Tauana sent me only data for one node. asked her for the rest of it for the other nodes. data looks complete
