### ISSUE TITLE
Water Sensors- EHC VA W

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#243]
This site went completely offline on 07/06/2022. The signal strength of the last transmission was less than -69 for all components. 

Do we know if this site is printing data? Can we get this site back online?

**Comment by saseehav** [comment]
@ethansweep is contacting Cynthia 7/21 with suggestions about resetting - Esleyther suggests taking this farm offline. If farm is +2weeks offline no evidence that it will re-connect.

**Comment by ethansweep** [comment]
Emailed Cynthia the following: 

This field site hasn’t been communicating with the tech dashboard since 07/11/22
- The signal strength for this field does not look very good, so there are probably some cellular connectivity issues preventing the gateway from communicating

The Rep 1 Bare node was not sending data from the three sensor depths, until the very last day it communicated
- Before that it was only sending data from the surface sensor, which can be seen in the chart view for this field
- Try resetting the nodes and gateway one more time to see if it will stay connected to the tech dashboard

Print off the logs for this field from the nodes and gateway and email them to Ethan 

While plugged into the gateway set it to “Receiver Mode”

**Comment by ethansweep** [comment]
Cynthia is out of town so Kevin Bamber from VA Tech contacted me about this field today.

Basically, the gateway was placed at the edge of the field near a wooded area that was logged within the last month. When they were logging the area the company must have hit the gateway and attempted to stand it back up, but Kevin found in on the ground and full of water. By the time I talked to him Kevin was already drying it out. I told him to hold onto it so that we can see if the SD card is able to be salvaged.

@elhenriq Would you please send a new gateway to Cynthia for this field?

**Comment by elhenriq** [comment]
will get one ready and ship it tomorrow 7/29/2022 to Cynthia with new battery and new SIM card.

**Comment by elhenriq** [comment]
New gateway shipped today to Cynthia. it should be as simple as place in the farm. reset all nodes and put this gateway there. she will have to fill up a new installation form. and on device status page it will show up as 1724921
