### ISSUE TITLE
DJL mixed up nodes

### ISSUE THREAD

**Issue by AlstonBetts** [precision-sustainable-ag/On-farm-Protocols#260]
Noticed an issue with DJL 
The chart view is reading data fine, but in device status view the depths are reading 999 for two nodes: 491 and 359. Is the best option for them to let them keep running as is, or will this cause a problem in the data collection?

**Comment by elhenriq** [comment]
I looked at them with Alston and notice that they put the node that we address as bare 2 in the cover 1 one spot and vice versa. when they scan the nodes on installation form, they did scan them on the proper spot for installation. we agreed on leaving them on the spots they are and not asking to swap this late in the season. @brianwdavis are you using the letters to populate the graphs instead of the depth? if that's the case, we can leave as is.

**Comment by brianwdavis** [comment]
I use the letters, but not the case, so "a" and "A" are treated the same for the depths. If you scanned it as a cover node in the install form and it's in the cover plot, it should be going into the DB correctly. Fixing the depths from `-999` (which becomes `NULL` in the DB) happens every couple of days in batches.
