### ISSUE TITLE
Water Sensors: Delaware esp QKZ

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#279]
#205 CFZ 
also, JVU (soybean/peas)

QKZ site collected 07/27/2022 to 07/30/2022. Site appears to have been reset. All came on at the same time and went off at the same time. Do we know what is going on at this site. Was there a data download? If so was it uploaded?

**Comment by elhenriq** [comment]
contacted them, still waiting for a response

**Comment by elhenriq** [comment]
Talked to Shawn about this farm. 

BT2, BT1 are collecting data just fine. CT2 is collecting data but is missing some TDRs (d and temp) 
the remaining CT1 was not downloaded because it started raining. will get data next time.

I was able to check on the data and talked to Shawn about checking the cables on the sensors. most likely they were cut by and animal.
