### ISSUE TITLE
Water Sensors: XTS Indigo Brooke (1084053)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#339]
Site is completely offline as of 5/30

**Comment by elhenriq** [comment]
have to visit farm and reset. download data and most likely set to receiver only!

**Comment by kldriver** [comment]
R1C offline as of 6/13. Poking Brooke today.

**Comment by saseehav** [comment]
1. When the device came back online online 6/6. Device reset by Brooke - tagged in this issue for this farm, and confirmed via email. Did not take devices offline. They are sending data 6/6 to 6/16.
@elhenriq why do you suggest set to receiver mode only as the default solution when the nodes go offline? Do they not collect data when attempting and failing a cellular send cycle? 
2. Where are people putting or sending manually downloaded node and gateway data? @brianwdavis can this data get parsed during this season? Let's put a priority on parsing the downloaded files. 
3. Open the files to confirm full node collection @elhenriq @kldriver when requesting this receiver mode from users. 
4. Issue can be closed after putting in receiver mode AND confirming all nodes operate by opening downloaded files. Issue stays open when files are not downloaded or collected and stored.

**Comment by elhenriq** [comment]
This farm is receiving a completely new installation, the gateway at this farm is giving an error I have not experienced before. she has two extra sets, and she will do a reinstallation in here. 

1. they do keep collecting data, I ask for a receiver mode because that prompts the user to visit this farm regularly to download data. 
2. people send the data download to me and i check it and submit here https://drive.google.com/drive/folders/1-L0mjVtlEfQrDLej0rcetQ867ZZNO3Nr?usp=drive_link
3. yes i do!
4. will do

**Comment by kldriver** [comment]
Rep 1 C deep sensor is offline
Rep 2 B top sensor is offline

**Comment by brohrigindigo** [comment]
I replaced both of these last week as well

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kldriver** [comment]
Site online.

**Comment by elhenriq** [comment]
@brianwdavis @kldriver Bare rep 2, the top sensor was replaced at some point but broke used a sensor from a different treatment for it and the letter is lowercase instead of uppercase, so the dashboard is not plotting that line. can you change that one, so it reads of the letter and not the depth, so it can plot it?

**Comment by elhenriq** [comment]
no data for a while, asking to download soon

**Comment by kldriver** [comment]
Available data downloaded at end of season.
