### ISSUE TITLE
Water Sensors: WVI Indigo Brooke (1022436)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#349]
Whole site is completely offline as of June 4

**Comment by elhenriq** [comment]
reset download and set to receiver only (most likely)

R1C for this farm needs a new b (middle) sensor. 
R1B a (top) sensor needs to be checked up, reading 5% water d (surface) also needs to be checked and make sure is all the way in 
R2C A (top) sensor is reading very low, should check is all the way in

**Comment by kldriver** [comment]
Poking Brooke today.

**Comment by kldriver** [comment]
Following up today.

**Comment by kldriver** [comment]
Site is mostly online. Missing a node, unable to discern which one.

**Comment by elhenriq** [comment]
Brooke replaced all nodes at this farm on 6-30 because they were having big issues. I was looking for a sensor install form for it, but she has not submitted one. I contacted her about submitting a new installation form. 
she sent me data for from the new nodes and I have already submitted to the drive. all data looks good up to 7-12

**Comment by elhenriq** [comment]
no data after reinstall, asking Brooke what happened. it could be related to issue #348 where it seems two installation forms have been submitted. @brianwdavis

**Comment by brohrigindigo** [comment]
Just submitted the reinstall form for WVI

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kldriver** [comment]
Shepherds: ensure both sets of nodes are accounted for as WVI.

**Comment by kldriver** [comment]
nothing more to be done.
