### ISSUE TITLE
Water Sensors: KDH DE (1084058)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#364]
Rep 2B deep sensor is offline. Whole rep is offline completely now. 
Rep 2C rep is completely offline

**Comment by elhenriq** [comment]
do a reset and download data from rep cover 2.

**Comment by kldriver** [comment]
Followed up with Sean today. Hi Shawn, 
Have you had a chance to head out to KDH? Esleyther recommends a download of rep 2 (remember to open the file to ensure it is a complete download) and a reset of rep 2. 
Feel free to call the hotline from the field if you need assistance.

**Comment by kldriver** [comment]
Following up today.

**Comment by kldriver** [comment]
Site completely offline 7/9, Reo 2 Bare had no deep sensor online before the site went completely offline

**Comment by elhenriq** [comment]
R1C 
I sent you a temp sensor for this farm, so you could replace the temp sensor since it is not working at the moment. 
R2C
this node has never made connection with any of the sensors, there is a physical break between the sensors and the node so the sensors can't be read by the node. check all the cables and the junction box to make sure all is fixed.

**Comment by elhenriq** [comment]
not communicated in a while, asking to get data again.

**Comment by kldriver** [comment]
all available data downloaded at the end of the season.
