### ISSUE TITLE
Water Sensors: PHZ NH

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#366]
This site as a whole is really irregularly sending data. Need download to see if node and gateway are receiving more data than sending.

**Comment by elhenriq** [comment]
very spotty signal, should download data and share with me. not needed to put on receiver mode. please download from all devices including nodes and gateway

**Comment by kldriver** [comment]
Site is online.

**Comment by elhenriq** [comment]
sent info to the team

R2C 
the deep sensor for this treatment has stopped working since 6-28 
R2B 
top sensor for this treatment has stopped working since 6-28also, all the sensors have been renamed while trying to print the data. HAVE TO change this back to normal ASAP. A was change to "p"; B was change to "a"; C was change to "t". have to change them on reverse. 
R1B 
top and surface sensors for this treatment stopped working since 6-28 
R1C 
surface and temp sensor for this treatment stopped working since 6-28
it is very strange how all the nodes have a sensor that stopped working on the same day. either an animal went through and chew all of them, or there is something else going on. please go ASAP and get them looked at. please call the hotline when you visit, so we can troubleshoot. **

**Comment by elhenriq** [comment]
asking to download data, data is very spotty.

**Comment by kldriver** [comment]
Available data downloaded at end of season.
