### ISSUE TITLE
Decomp bag biomass amounts for sample analysis

### ISSUE THREAD

**Issue by ethansweep** [precision-sustainable-ag/On-farm-Protocols#43]
Customer: Lindsey Ruhl, Vermont

Lindsey called to say that the amount of biomass they have ground up from their T0 samples is about 8-10 grams and she was wondering how much sample we needed for the C:N analysis. She allocated 6.5 grams to the ashless weights and NIR, with the rest going into the scintillation vials for C:N. I told her to put the rest of the sample into a scint vial for C:N, but in the future to prioritize samples for C:N analysis over the ashless weights. This is something that Resham directed us to do with some of our smaller samples.

Do we have any numbers for the minimum amount of sample needed to accomplish each of these analyses? For example, do we need a full 20 ml sample for the NIR, or would it be ok with 2 grams? I don't know if these need to go in the protocol, but they would be nice to have. 

I'm also a little concerned about this site going forward. If they only have ~10 grams of sample from the T0 bags, they're probably going to have really small amounts of biomass by T3.

**Comment by saseehav** [comment]
@ethansweep Ethan - this is a great response. 
I am going to tag the rest of the on-farm hotline squad so everyone is comfortable with this, since I have got other questions about sample size.  @brianwdavis @elhenriq @aidabagheri @annabirnbaum 

And Lindsey emailed me as well, and this was my response:

Sample priority:
NIR - a single sample (T0-A or B) 5 grams
C/N - scint vial - analysis only takes about a thimble full of sample (~10 mg)
Ash 1 gram bag - (ash can take as little as 0.5 grams, or even less)
Then save any remaining in archive.

Samples can be pretty small and still have enough for everything. 8 to 10 grams is more than enough to do all analysis. No one should be overly concerned about sample size - even as the bags start decomposing. To successfully get both CN AND Ash we still only need less than a gram per sample.
