### ISSUE TITLE
Tablet lost esper provision

### ISSUE THREAD

**Issue by zackgrzywacz** [precision-sustainable-ag/On-farm-Protocols#447]
PMC in Missouri called and said their tablet lost esper provisioning. I will contact them and organize getting esper back on their tablet

**Comment by saseehav** [comment]
@zackgrzywacz i can do this tomorrow. do you have an associated phone number they want you to call them on or should I arrange with them over email?

**Comment by zackgrzywacz** [comment]
@saseehav they called me from (816) 809-6457. I can also take care of it tomorrow if you're busy

**Comment by saseehav** [comment]
We factory reset Jason's tablet (KS PMC), and he scanned a QR code for a new provisioning. 
He told me that he was on the cellular data system, when the tablet asked to approve an update. He updated it. The next time he went online to receive a plantmap3d app update as instructed, he turned the 4G cellular data on, say the blue screen like normal, and then the tablet reset itself. This is when he called Zack. 
Sarah will finish provisioning remotely tomorrow.

**Comment by saseehav** [comment]
Talked with Esper - they see that a command to wipe the device was sent on Feb 20. this was due to failures to effectively get a blueprint to converge. The command didn't reach the device until April, already after he had collected some data. 
Esper doesn't know how to proceed. They think it is rare. 
Solution: allow many days on a strong wifi network to finish a converge or actions.
