### ISSUE TITLE
all farm sets shipped before 4-14 might have a bad or not working well firmware on the gateway

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#66]
Sets shipped to AL, DE, FL, GA, IN, KS and NE have an old version of the firmware. I know for a fact the one set in NE does will try to work to get them updated soon. They were shipped before the latest software came out (4-14) this problem is really noticeable on gateways using firmware for 3-15. 

Working on updating AL at the moment will work with NE next. The only way to do this is on a computer, unfortunately. Kip is sending his nodes to us in NC because his computer doesn't allow for the app to run.

**Comment by annabirnbaum** [comment]
Do we need to tell these folks to hold off installing? Is this the same issue that Ethan reported at Missouri yesterday?


Anna Paulk Birnbaum

Agricultural Specialist
UGA-Department of Crop and Soil Sciences
1420 Experiment Station Rd
Watkinsville, GA 30677
C: 404-889-1688
________________________________
From: elhenriq ***@***.***>
Sent: Tuesday, May 18, 2021 5:51 PM
To: precision-sustainable-ag/On-farm-Protocols ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [precision-sustainable-ag/On-farm-Protocols] all farm sets shipped before 4-14 might have a bad or not working well firmware on the gateway (#66)

[EXTERNAL SENDER - PROCEED CAUTIOUSLY]


Sets shipped to AL, DE, FL, GA, IN, KS and NE have an old version of the firmware. I know for a fact the one set in NE does will try to work to get them updated soon. They were shipped before the latest software came out (4-14) this problem is really noticeable on gateways using firmware for 3-15.

Working on updating AL at the moment will work with NE next. The only way to do this is on a computer, unfortunately. Kip is sending his nodes to us in NC because his computer doesn't allow for the app to run.
