### ISSUE TITLE
sensors in NE

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#70]
Tauana called today, her gateway has is sending spotty data, she will restart next time she visits the farm.

**Comment by ethansweep** [comment]
Tauana called today after she had reset the nodes and gateways. The gateway was still not connecting to the tech dashboard, and the last time it sent data is 5/23. There was no timestamp update from when she reset the system.
I ran through the typical diagnostics and everything sounds like it should be in good working order, but nothing shows up. Could it possibly be a cell reception issue? Doesn't the gateway need a certain amount of strength to send data?

I told her that others were having similar issues and that someone (possibly @elhenriq) would follow-up with her in the morning.

**Comment by elhenriq** [comment]
Yes, this is definitely because of cell connection issues, don't have a clear path to follow to fix this, the same thing is happening in multiple locations. Need @alondrathompson opinion on this.

**Comment by alondrathompson** [comment]
@ethansweep This does sound like a cellular reception issue. If you feel comfortable, either you or Esleyther could walk her through using the cellular scouting mode to verify. Otherwise, have her check the SD card to make sure that the gateway is receiving data from the nodes. If not, have her connect to each node and to check the data. 

Also, what is the device ID for this gateway?
