### ISSUE TITLE
AL Gateway not connecting

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#71]
Kip called me directly.  He installed sensors set with gateway ending in 193 today, turned everything on and isnt showing up on dashboard. 

He already updated the firmware on this set with Esleyther. 

He has to go back to farm tomorrow anyway, will reset, and i am going to help him go through synching using his tablet if needed.

**Comment by annabirnbaum** [comment]
His gateway started sending data and a backlog of data this morning at 7am. He didnt reset it, it just happened.

**Comment by annabirnbaum** [comment]
Kip's gateway sent data from 7am-2pm on 5/25. Has only been sending data from 3/4 nodes.  

I tried to help him troubleshoot. 1. connected the node that isnt showing up on dashboard to tablet, node is working, but not synching to gateway
2.connected gateway to tablet (got stuck in loop trying to connect to hologram)
3.tried cellular scouting (reported GOOD signal)
4. tried to synch again and got stuck in loop trying to connect to cell again, never pinged nodes

I called Esleyther, he said similar thing happening in VA, he is going to talk to Alondra when she gets back.  I think Tuwana is having similar issue?

Kips other set he installed yesterday isnt conneceting to dashboard either.  He isn't going to go reset it until this issue gets sorted. 

@elhenriq

**Comment by elhenriq** [comment]
Don't have a clear understanding of the issue, I have experienced the same problem but can't figure out what is going on. As for the device that doesn't appear in the dashboard it is because it has never connected to the internet. Needs to be plug in with tablet to make sure it connects to the network.

**Comment by alondrathompson** [comment]
@annabirnbaum @elhenriq 
The gateway shouldn't be getting stuck in loop trying to connect to Hologram. It will try a few times, I don't remember how many, but it should eventually give up and try to connect to the nodes. I'll double check the firmware. 

Just to make sure I'm understanding, this issue is that the gateway has good cellular reception, but it's getting stuck in an infinite loop?

**Comment by annabirnbaum** [comment]
This set seems to be working now.  Issue solved.
