### ISSUE TITLE
VA Eastern Shore Team Device View Not working VA1

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#74]
oy, big day.  

Joseph Haymaker in Eastern Shore VA,  called around 3:30.

1. He said they can not see any data in device status view for any of their farms/gateways, he says Blacksburg team has same issue (Ethan logged this yesterday I see). I can see the devices. 
 @brianwdavis @saseehav  

2. I forget when he said he installed the sensors (sometime this week, maybe today, idk im dehydrated). Anyway, I could see data wasn't coming into the dashboard. I had him plug his tablet in to the gate way and was walking him through synching it. When he plugged in the tablet he got weird text (no menu, image attached). He tried disconnecting and reconnecting but got same weird text.  Meanwhile, I noticed the gateway started sending old data to the dashboard from May 13, and only from one treatment.  I had him reset everything. Within 30 min it started sending todays data to the dashboard.  @alondrathompson 

3. The set he installed yesterday  (1022431) is sending some spotty data, mostly gateway datastrings.  He was going to go reset but told him to hold off until we get stuff figured out.
![thumbnail_Screenshot 2021-05-26 at 4 44 59 PM](https://user-images.githubusercontent.com/64480167/119728737-ce67e880-be41-11eb-96a9-fb3e12951b34.png)

**Comment by alondrathompson** [comment]
@annabirnbaum The weird text is probably due to a baud rate mismatch between the gateway and the serial monitor. The serial monitor should be set to 57600 baud.

The gateway (1022431) looks to have lost communication with all of the nodes. The signal strength for the cellular reception has also gotten worse. I'd suggest:
- Check that all the antennas are straight up (perpendicular to the horizon) 
- Raising the gateway higher
- Move gateway closer to nodes (if possible)
- Raising the nodes higher (if possible)
